javascript:function form_fillup(){                 
  var things =  ['DEEPA RANI AIND','SUPRIYA RAJ SINGH','ANUSHREE SUMAN','MONU SOREN','SUMAN TIGGA','SHRUTI KUMARI','SHIVANI KUMARI SONI','LOVELY KUMARI','KIRAN KUMARI','ANUSHKA MOHANTY','NARGIS ZEBA','DEEPANJALI LAKRA','SUJATA KUMARI','MONIKA KUMARI','RIYA KUMARI','SANGEETA KUMARI','MAUSAM KUMARI','KOMAL KUMARI','FALAK AARZOO','ANKITA KUMARI','SUSHMITA LAKRA','ASTHA KIRAN','RIYA KUMARI','SUMAN KUMARI','RIYA KUMARI','PRIYA KUMARI','PUJA KUMARI','RUCHI PRAKASH LAXMI','SUSHMITA BARA','HAILRY LAKRA','SANTOSHI MINZ','SANGEETA KUJUR','SWATI  TOPPO','SWATI ORAON','ARTI BARAIK','INDU KUJUR','RANJANA MINJ','KHUSHBOO KUJUR','PRITI POONAM','PUSHPA KUMARI','NEHA TIRKEY','TULIKA KUMARI','SAIDA KHATOON','KRITI KUMARI','SURBHI KUMARI','ANJALI KUMARI','KAJAL KUMARI','ANITA KUMARI','PRIYA KUMARI','JUHI KUMARI','PALLABI DAS','PALLABI DAS','GURUWARI TUDU','BINDU KUMARI','RUPA KUMARI','ASMIKA DEBGOSWAMI','ALISHA LAKRA','SANDHYA KUMARI','DOLLY KUMARI','ITISMITA GIRI','PRIYA SINGH','ARCHNA KUMARI','MAHIMA MAHATO','NIKHAT PARVEEN','KHUSHBOO KUMARI','TUSHA','DEEPIKA KUMARI','JAYA KUMARI SINGH','SABA FARHEEN','MANISHA KUMARI','KHUSHBU PARWEEN','USHA KUMARI','BEAUTY KUMARI','RADHA KUMARI','SARASWATI KUMARI','SWETA SOUMYA','MUNDA MADHU','HIRAMANI MUNDA','LAXMI TIRKEY','KUSUM KUMARI','REEMA KUMARI','ARCHANA ORAON','RUBY KUMARI','VINEETA KUMARI','MONIKA KUMARI','PRIYANKA KUMARI','RADHIKA KUMARI','SAROJ NAG','SUSHILA KUMARI','BHAWANA PODDAR','RIMPA SARKAR','SUPRITI MAHATO','ASMITA RUP','NISHI HASSA','NEHA KUMARI','MANISHA KUMARI','VIDYA KUMARI','SWETA RANI','AMISHA NIKITA DANG','SHEELA HANSDA','BARKHA KUMARI','TAPASWINI ROUT','MAHIMA KACHHAP','BHUMIKA KUMARI','PRITI RANI','RITU KUMARI','MANISHA KUMARI','SIMA KUMARI','SWASTI MISHRA','ANJALI KUMARI','AYUSHI ARYA','TAHSEEN PRAVEEN','BHAWNA NIDHI','ANKITA KUMARI RAM','SEEMA KUMARI','SIYA KUMARI','PRIYA DAS','AMRITA ORAON','SUSHMA TIRKEY','ANSHU JOYSI SANGA','NEHA KACHHAP','NIVEDITA HEMBROM','OLIFE TOPNO','SHRISTI LAKRA','KAVITA KUMARI','SANGITA KUMARI','MANISHA KUMARI','BINITA KUJUR','MANISHA LAKRA','JAYA KUMARI','KUMARI RITU','BHAWANI MEHTA','NEHA KUMARI GUPTA','SUJATA KUMARI','PAYAL KUMARI','YOGYANTI GOPE','SHRISHTY KESHRI','ADITI ARYA','BABLI SAHU','KALASHPREET KAUR','SWETA KUMARI MAJHI','SUBHASINI KUMARI','BITTU KUMARI','ARPITA KAR','PRITI DHAN','SUSHMITA SINGH','SANTOSHI KUMARI','SMITA ARYA','ANMOL MUNSHI','NAMITA BAXLA','SNEHA TETE','DEBOLINA DAS','SUSHMA KUMARI','NISHA RANI','NISHA RANI','SUNAINA KUMARI','AMISHA','ISHANI DEY','ANUPREETY TETE','SANTOSHI KUMARI','SURBHI RANI VERMA','RITU KUMARI','MANJU PURTY','AKRITI SINGH','SUNAINA KUMARI','PRIYANKA KUMARI BARAIK','PRIYA KUMARI','RADHIKA TANI','SWETA KUMARI','SONI BHARTI','AMRIN BANO','KOMAL KUMARI','SONU SINGH','NOORJAHAN PARWEEN','VAISHNAWI KUMARI','PRERANA SINGH','MONIKA KUMARI','AMISHA KUMARI','KAJAL KUMARI','NEETA KUMARI','ANKITA KUMARI','SAKSHI JHA','BHARTI KUMARI','SHRISTI SUMAN','PALLAVI PRIYA','SUMAN BHARTI','ANJALI KUMARI','PALLAVI KUMARI','AANCHAL GORAI','PRIYA KUMARI PANDEY','ARUNIMA KUMARI','ZEENAT PARWEEN','ANJALI KUMARI','KHUSBOO KUMARI','SUCHITA KUMARI','KUSUM KUMARI','MUSKAN BHARTI','KAJAL KUMARI','ADITI PRIYA','SHALINI KUMARI','MANISHA KUMARI','ROSHNI KUMARI PRASAD','ROSE','SUMAN KUMARI','MONA KUMARI','SALONI RAJWAR','NEHA KUMARI MIRDHA','SHIKHA KUMARI','GURIYA KUMARI','RAVEENA PASWAN','KAJAL KUMARI','SUPRIYA KUMARI','KARISHMA PANNA','SANJANI ORAON','RAKHI KUMARI MUNDA','SUSHANTI ORAON','RASHMI PAHAN','SWATI KUMARI','ANNU KUMARI','CHINTRA OREYA','ASHU ANUPA KUJUR','SUJATA HEMBROM','SUDHA SUSANA MARANDI','SUPRIYA KACHHAP','NIDHI SALOMI TUTI','SUSHILA KUMARI','SHEELA KISKU','SANGITA KUMARI','SAROJNI TOPPO','SONY MINZ','RIYA KACHHAP','SHIMLA KUMARI','ALINA KISPOTTA','SONY KISPOTTA','DIPIKA KUMARI','PRIYANKA KUMARI','ARCHANA MINZ','BINITA KUMARI','KUSUM KUMARI','PRIYANKA PURTY','SHOBHA TOPPO','RANI KUMARI','MAMTA KUNKAL','PINKI KUMARI','MUSKAN KUMARI','NANDANI KUMARI','GAYATRI KUMARI','RUPA RANI','FARHA PARWEEN','NEHA  KUMARI','ZAIBA NURI','PUJA KUMARI','KAJAL KUMARI','RIYA KUMARI','NEHA PERWEEN','KOMAL KUMARI','GITIKA KUMARI','AARTI KUMARI','SARASWATI KUMARI','TANUSHRI KUMARI','SUMAN KUMARI','AKANKSHA SINGH','SNEHA SAHU','RAKHI KUMARI','SHIWANI CHOUDHARY','RUPA KUMARI','SHREYA DEOGHARIA','SHRUTI KUMARI','ANJANA KUJUR','RIYA  GOPE','SHIPRA NATASHA KUJUR','SALONI SINGH','PALLAVI DAS','SWETA KARMAKAR','LATA KUMARI','JAISHREE SAHI','PREETI KACHHAP','ANAMIKA TUDU','PURNIMA KUMARI','NEHARIKA KUMARI BARAIK','ARSHI SHIFA','ANUPAM SHRISTI','ANJUM PARWEEN','ANJALI KUMARI','MADHURIMA BAKHLA','HRISHITA ROY','NIBHA ORAON','NIRIYA BARI','ANSHUMALA HEMROM','PRERNA RAJ','SAGUFTA SUMBUL','AHALI ROY','NITI VERMA','POONAM SINGH','TANIYA KUMARI','TASMIYA','SUPRIYA KUMARI','ANJU KUMARI','NISHA KUMARI','MANORAMA DUSADH','PRIYA RANJAN','SONALI KUMARI','NEHA KUMARI','SUPRIYA ZINAL TOPPO','BHARTI KUJUR','SUMAN KUMARI','NISHA OLIVIA MARANDI','ARGEN BAXLA','ANJALI KANTA KERKETTA','SIMANTA  ORAON','ROSE KINDO','ROSEWEL TUDU','SIMRAN DICKCHA TOPPO','KAVITA MINZ','PUJA RANI TIGGA','KAJAL LAKRA','RUBI KUMARI','NANCY ROSELIN MARANDI','ISHA MADHU LAKRA','ANURADHA LAKRA','KIRAN KHUSHBOO BAXLA','GEETA KUMARI','ARTI KUMARI','SHABNAM KHATOON','ANJALI GOPE','KOMAL SHARMA','UMUL KHAIR FATMA','NISHA BHARTI','MANISHA BHARTI','BARSHA MAHTO','ANSHU GIRI','SOUMYA KUNDU','LALITA SINGH MUNDA','DEEPSHIKHA KUMARI','MARY KANDULNA','KASHISH PODDAR','PRITY KUMARI','GEETA BECK','NITU ROSE MINJ','PRIYANKA KINDO','PRIYA CHOUHAN','NIRMALA BINJHA','SURABHI KUMARI','ANANYA','PRAMILA KISKU','NITIKA KUMARI','FARHEEN TABASSUM','SHRADHA SUMAN','DIPTI KUMARI','KOMAL KUMARI','KUMARI RIYA','JYOTI KUMARI','PREETY MINZ','NISHA KUMARI SINGH','RUPALI BARA','REENA KUMARI','ANKITA KUMARI','NANDANI KUMARI','ANISHA NAG','DIMPLE KUSHWAHA','SHAKSHI SINGH','ANUKAMPA KUJUR','SANGEETA KUMARI','APRAJITA JEET','SURBHI KUMARI','AMISHA DHAN','PRIANA EKKA','ANGEL SHARON KUJUR','CHANDMANI KUMARI','LOVELY ANAND','PRATIVA KERKETTA','AMITA KIRO','POONAM KUMARI','ANIMA KINDO','PRATIBHA BHAGAT','NEHA KUMARI','JYOTI TIGGA','ANU KUMARI','SAPNA MUNDUIYA','SHABNAM BAKHLA','RESHMA TETE','ASMITA SURIN','SALOMI HEMROM','ANJU KACHHAP','GORETI TIRKEY','PURNIMA KUJUR','SUNITA MUNDA','RIMA KUMARI','SABITA KUMARI','RAKHI KUMARI','RIYA GUPTA','SWETA KUMARI','JYOTI KUMARI','NEELAM KUMARI','ANJALI KUMARI','SHIWANI KUMARI','JULEE KUMARI','SONALI KUMARI','KRITI VERMA','AARTI KUMARI','ARCHANA KUMARI','MUSKAN KUMARI','SOUMYA KUNDU','LALITA SINGH MUNDA','DEEPSHIKHA KUMARI','MARY KANDULNA','KASHISH PODDAR','PRITY KUMARI','GEETA BECK','NITU ROSE MINJ','PRIYANKA KINDO','PRIYA CHOUHAN','NIRMALA BINJHA','SURABHI KUMARI','ANANYA','PRAMILA KISKU','NITIKA KUMARI','FARHEEN TABASSUM','SHRADHA SUMAN','DIPTI KUMARI','KOMAL KUMARI','KUMARI RIYA','JYOTI KUMARI','PREETY MINZ','NISHA KUMARI SINGH','RUPALI BARA','REENA KUMARI','ANKITA KUMARI','NANDANI KUMARI','ANISHA NAG','DIMPLE KUSHWAHA','SHAKSHI SINGH','ANUKAMPA KUJUR','SANGEETA KUMARI','APRAJITA JEET','SURBHI KUMARI','AMISHA DHAN','PRIANA EKKA','ANGEL SHARON KUJUR','CHANDMANI KUMARI','LOVELY ANAND','PRATIVA KERKETTA','ANIMA HERENZ','SANGEETA  PRADHAN','DEEPSHIKHA KUMARI','SONALI RANI','ANJALI KUMARI','SANJANA GARI','JULI KUMARI','TRIPTI JHA','ISHITA DAS','SRISHTI KUMARI','ANCHAL SINGH','RAKHI KUMARI','BHAGYASHREE KUMARI','ANJALI LAKRA','NEHA KUMARI','APARNA MAHATO','BHAWANI SINGH MUNDA','NEHA BECK','ASHA KUMARI','SANTOSHI KUMARI','KARUNA KIRAN HANSDA','NITI LAKRA','ARTI KUMARI','NEHA TIRKEY','ARADHYA KESHAV','SAKSHEE AANAND','AARTI KUMARI','PRAMILA KUMARI','NISHA KUMARI','CHANDRAMANI KUMARI','KANCHAN MUCHU','PUNAM KUMARI','ANJU TOPPO','ELIN BECK','VIKRANTI KUJUR','SHARDA PURTY','RITU LOVELY TOPNO','BINITA LAKRA','AMRITA TOPNO','SEEMA KUMARI','ANJALI KUMARI','DIVYA TIRKEY','ANGEL ROMA TOPPO','BINA MINJ','RAINI BARJO','JYOTI DHAN','PRIYANKA KUMARI MAHTO','MALTI KUMARI','NIKITA KUMARI','MANSI KUMARI','DEEPIKA KUMARI','SUMAN KUMARI','RIKEY KUMARI','REEFAT KHATOON','AYESHA SIDDIQUA','SHILPA KUMARI']; 
  let thing = things[Math.floor(Math.random() * things.length)];
  let name =thing.split(" "); alert(name);
  let first_name = name[0];
  let last_name = name[1];
  console.log(first_name);
  console.log(last_name);
  alert(last_name);
  let counts=setInterval(updated,1000);
  let i = 1;            
  function updated(){
    i++;
    if(i==2){
      function changeValue(input,value){
        var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value").set;
        nativeInputValueSetter.call(input, value);
        var inputEvent = new Event("input", { bubbles: true });
        input.dispatchEvent(inputEvent);
      }
      changeValue(document.querySelector('input[data-automation-id="First Name-input"]'), first_name);
      changeValue(document.querySelector('input[data-automation-id="Last Name-input"]'), last_name);
    }
    else if(i==6)
      {
        document.querySelector('button[data-automation-id="Age-select-btn"]').click();
      }
    else if(i==8)
      { 
        document.getElementById("field-option-14-18").click();
      }
      else if(i == 10)
        {
          document.querySelector('button[data-automation-id="profile-options-done-button"]').click();
        } 
        else if(i == 12)
        { 
           document.querySelector('button[data-automation-id="Gender-select-btn"]').click();
        }
        else if(i==14)
        { 
            document.getElementById("field-option-Fema").click();
        }
        else if(i==16)
        {
            document.querySelector('button[data-automation-id="profile-options-done-button"]').click();
        }
        else if(i==18)
        {
         document.querySelector('button[data-automation-id="State-select-btn"]').click();
       } 
       else if(i==20)
        {
          document.getElementById("field-option-Jharkhand").click();
        } else if(i==22)
        { 
          document.querySelector('button[data-automation-id="profile-options-done-button"]').click();
        } 
      } 
    }form_fillup();